[Unit]
Name = "komorebi-bar-1"
Description = "Status bar for komorebi - Monitor 1"
Requires = ["komorebi"]

[Service]
Kind = "Simple"
Environment = [[
    "KOMOREBI_CONFIG_HOME",
    "$USERPROFILE/.config/komorebi",
]]
Restart = "Never"
Autostart = false

[Service.ExecStart]
Executable = "komorebi-bar.exe"
Arguments = [
    "--config",
    "$USERPROFILE/.config/komorebi/komorebi.bar.1.json",
]

[Service.Healthcheck.Process]
DelaySec = 1

