[Unit]
Name = "masir"
Description = "Focus follows mouse for Windows"

[Service]
Kind = "Simple"
Restart = "OnFailure"
Autostart = false # Started by altsnap

[Service.ExecStart]
Executable = "masir.exe"

[Service.Healthcheck.Process]
DelaySec = 1
