[tools]
chezmoi = "latest"
starship = "latest"
node = "lts"
go = "latest"
lazydocker = "latest"
tmux = "latest"
python = "3.12"
rust = "latest"
"cargo:git-profile" = "latest"
lazygit = "latest"
delta = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
