# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml
#
# ### Variant 2: two line prompt, no background in top line, separators on left side
# *** Borrowed from a design seen in a zsh (should be from https://github.com/romkatv/powerlevel10k)
#
# - No filling solid line in top row: 
#   Replace '$fill\' with just one character '\' or just completely delete the line that contains '$fill\' further down,
#   within the format-block: format = """ ... """.
#
# - '$line_break': everything from the next line on refers to the second line of the prompt.
#
# - Some modules listed further down will not show up (all the time), as their default value is 'disabled = true' or
#   they are only displayed under certain conditions.
#
# - Symbols:
#   Don't be confused if you see this toml file via web browser on a website, gist, ... and you don't see any "real" symbols further down.
#   If Nerd-fonts are already installed on your system (e.g. MesloLG Nerd Font, FiraCode Nerd Font, ...) it should work.


palette = "catppuccin_mocha"

# Customizing the prompt (and placing desired modules at desired position and sequence):
format = """
[â•­â•´](fg:surface2)\
$os\
$sudo\
$directory\
$terraform\
$python\
$git_branch$git_commit$git_state$git_metrics$git_status\
$jobs\
$memory_usage\
[ ](fg:white)\
$cmd_duration\
$fill\
$username\
[@](fg:bright-black)\
$hostname\
$time\
$line_break\
[â•°â•´](fg:surface2)\
[$status\
$localip\
$character]($style)\
"""

right_format = """
[<â”€â”€â•¯](fg:surface2)
"""

# Inserts a blank line between shell prompts:
add_newline = true

# Customization and activation of some modules:
# Listed in the order of their position in the module row above
[os]
format = "[$symbol ]($style)[ ]()"
style = "fg:white"
disabled = false

[os.symbols]
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "îœŽ"
Arch = "ïŒƒ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "ðŸ‰" # "îž†"
Emscripten = "ðŸ”—"
EndeavourOS = "ïŒ¢" # "ïž»"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Garuda = "ï…¼"
Gentoo = "ïŒ"
HardenedBSD = "ï¦—"
Illumos = "ðŸ¦"
Linux = "ï…¼"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Mariner = "ï…¼"
MidnightBSD = "ðŸŒ˜"
Mint = "ïŒŽ"
NetBSD = "ï…¼"
NixOS = "ïŒ“"
OpenBSD = "ïŒ¨" # "ï…¼"
OpenCloudOS = "â˜ï¸"
openEuler = "ï…¼"
openSUSE = "ïŒ”"
OracleLinux = "âŠ‚âŠƒ"
Pop = "ïŒª" # "ï…¼"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Redox = "ðŸ§ª"
Solus = "ïŒ­" # "ï…¼ "
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ï„ˆ"
Windows = "îœ"

[username]
format = '[ î‚± ]($style)[$user]($style)[]()'
style_user = 'fg:white'
style_root = 'fg:red bold'
show_always = true
disabled = false

[hostname]
format = '[$ssh_symbol](fg:white)[$hostname](fg:white)[ ]()'
ssh_only = false
ssh_symbol = 'î®' # 'ï…½â‡’' # 'ï£· ' # 'ï¬â‡’'
#trim_at = '.companyname.com'
disabled = false

[sudo]
format = '[î‚± ](fg:red bold)[as $symbol]($style)'
style = 'fg:red bold'
symbol = 'ï”„ ' # 'ï”Š â¯ '
disabled = false

[directory]
format = '[î‚± ](fg:mauve)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[$path]($style)'
style = 'fg:mauve'
home_symbol = 'ï€• ~'
read_only = 'ï ½ ' # 'ï£­ ' # 'ï£® ''
read_only_style = 'fg:cyan'
truncation_length = 3
truncation_symbol = 'â€¦/'
truncate_to_repo = false
repo_root_format = '[î‚± ](fg:mauve)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
repo_root_style	= 'fg:mauve'
use_os_path_sep = true
disabled = false

[git_branch]
format = '[î‚± $symbol $branch(:$remote_branch)]($style)[ ]()'
style = 'fg:blue'
symbol = 'ïž¡'
#ignore_branches = ['master', 'main']

[git_commit]
format = '[\($hash$tag\)]($style)[ ]()'
style = 'fg:blue'
commit_hash_length = 8
tag_symbol = 'ï’ ' # 'ï€« ''
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ]()'
added_style = 'fg:blue'
deleted_style = 'fg:blue'
disabled = false

[git_status]
# place symbols before '$count'
format = '([$all_status$ahead_behind]($style))'
style = 'fg:blue'
conflicted = '[ï‘¯${count} ](fg:red)'
ahead = '[â‡¡${count} ](fg:yellow)'
behind = '[â‡£${count} ](fg:yellow)'
diverged = '[â‡•${ahead_count}â‡¡${behind_count}â‡£ ](fg:yellow)' # â‡• â†• â‡³ ó°¹¹ ó°¹º ó°§ˆ 
up_to_date = '[âœ“ ](fg:green)'
untracked = '[ï³‡${count} ](fg:red)' # 'ï° ' # '? '
stashed = '[ï›¢${count} ](fg:red)' # 'ðŸ“¦ '# 'îž› ' # 'ï’‡ ' # 'îœ ' # 'î¬‰ ' 
modified = '[ó°·‰${count} ](fg:yellow)' # 'ðŸ“' # '! ' # îž # ï‚­ # ïƒ
staged = '[ïƒ‘${count} ](fg:green)' # '+ '
renamed = '[ïžƒ${count} ](fg:yellow)' # 'ï—ˆ ' # 'ï«¦' # á´‚ # ï¤ # ïžƒ # ïƒŒ # ï³³
deleted = '[ï¯Š${count} ](fg:orange)' # 'ðŸ—‘ ' '- '
disabled = false

[jobs]
format = '[ î‚± ](fg:blue bold)[$number$symbol]($style)'
style = 'fg:blue'
symbol = 'ï¥­' # 'ïª‚' # 'ó°œŽ' # 'î®¢' # 'âœ¦'
symbol_threshold = 1
number_threshold = 4
disabled = false

[memory_usage]
format = '[ î‚± ](fg:purple bold)[$symbol ${ram} ${swap}]($style)'
style = 'fg:purple'
symbol = 'ï¬™ ï¥£' # 'ï¬™ ï§¥' # 'ï¬™ / ó°¾µ' # 'ó°› ó°¾µ' # 'ï¬™ ó°¾´' # 'ï¬™ ó°¾¶' # 'ï¬™ ó°¾·' 'ï¬™ ó°£‚'
threshold = 75
disabled = false

[cmd_duration]
format = '[î‚³ ï”Ÿ $duration ]($style)'
style = 'fg:white'
min_time = 500
disabled = false

[fill]
style = 'fg:surface2'
symbol = 'â”€'

[status]
format = '[$symbol$status $hex_status ï–› $signal_number-$signal_name ]($style)'
style = 'fg:red'
symbol = 'âœ˜ '
disabled = false

[localip]
format = '[$localipv4 ](fg:green bold)'
ssh_only = true
disabled = false

[time]
disabled = false
style = "bold bright-black"
format = "[î‚± $time](fg:bright-blue)[ â”€â”€â”€â•®](fg:surface2)"

[terraform]
format = '[î‚± $workspace@$version]($style) '
style = "fg:mauve"

[python]
symbol = 'ó°Œ  '
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"

crust = "#11111b"
